// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xchgmvpzygpenccnidtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaGdtdnB6eWdwZW5jY25pZHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTU5NDcsImV4cCI6MjA3MDc3MTk0N30.kF5p_UJjJF7CU4L5N6GHH6QU2R8DTpB9Z1g5BwCroC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});